import type { AppLanguage } from '../context/LanguageContext';

type Section = { heading: string; body: string };
type Document = { title: string; updated: string; intro: string; sections: Section[]; note: string };

export const legalDocuments: Record<AppLanguage, Record<'terms' | 'privacy', Document>> = {
  es: {
    terms: {
      title: 'Términos y condiciones',
      updated: 'Versión del 4 de octubre de 2026',
      intro: 'Estos términos regulan el uso de Swingers World, una plataforma para que personas adultas conozcan a otras personas. Leelos antes de crear una cuenta. La Política de privacidad es un documento independiente.',
      sections: [
        { heading: '1. Edad y cuenta', body: 'El servicio es exclusivamente para mayores de 18 años y de la edad legal aplicable en su lugar de residencia, si es superior. Debés proporcionar información auténtica, mantener tus credenciales en secreto y no ceder tu cuenta. Si creás un perfil de pareja, declarás que ambas personas son adultas, conocen el perfil y autorizan su publicación.' },
        { heading: '2. Consentimiento y seguridad', body: 'Toda interacción debe ser voluntaria y respetuosa. El uso de la app no implica consentimiento para ninguna actividad fuera de ella. Podés retirar tu consentimiento en cualquier momento. No compartas imágenes, mensajes o datos privados de otra persona sin autorización expresa. Evitá publicar información que permita identificarte o localizarte fuera de lo que querés mostrar.' },
        { heading: '3. Conducta y contenido prohibido', body: 'No se permiten suplantación de identidad, perfiles falsos, acoso, amenazas, discriminación, extorsión, explotación, contenido sexual no consentido, imágenes de menores, trata, prostitución o intercambio de actos sexuales por dinero u otros beneficios, spam ni actividades ilegales. No publiques contenido sobre el que no tengas derechos o autorización. El incumplimiento puede dar lugar a eliminación de contenido o suspensión de la cuenta.' },
        { heading: '4. Tu contenido', body: 'Conservás los derechos sobre el contenido que subís. Al publicarlo, nos autorizás de forma no exclusiva a almacenarlo, procesarlo y mostrarlo a las personas que correspondan según tus ajustes, únicamente para operar y proteger el servicio. Podés editar o eliminar tu contenido mediante las funciones disponibles, sujeto a las limitaciones técnicas y obligaciones legales aplicables.' },
        { heading: '5. Reportes y moderación', body: 'Podés bloquear o reportar perfiles y contenido desde la app. Podemos revisar reportes, restringir funciones, retirar contenido o suspender cuentas para aplicar estas reglas y proteger a la comunidad. No garantizamos una revisión previa de todo el contenido ni la identidad, intención o conducta de otras personas. Ante una amenaza inmediata, contactá a los servicios de emergencia locales.' },
        { heading: '6. Suscripciones y prueba gratuita', body: 'Los precios, duración, renovación automática y condiciones de una prueba gratuita se muestran antes de confirmar la compra en la tienda correspondiente. Si no cancelás antes de que termine la prueba, la tienda puede cobrar el período siguiente. La cancelación se gestiona en Google Play o App Store y normalmente conserva el acceso hasta el fin del período pagado. Eliminar la cuenta no cancela por sí solo una suscripción. Los reembolsos se rigen por las reglas de la tienda y la ley aplicable.' },
        { heading: '7. Disponibilidad y límites', body: 'Trabajamos para mantener el servicio disponible y seguro, pero puede haber interrupciones, errores o cambios de funciones. No garantizamos que encuentres personas compatibles ni el resultado de interacciones fuera de la app. Nada de estos términos limita derechos que no puedan excluirse por ley.' },
        { heading: '8. Cierre y cambios', body: 'Podés eliminar tu cuenta desde Cuenta. Podemos suspenderla por incumplimientos graves o riesgos de seguridad. Si cambiamos estos términos de manera importante, informaremos la nueva versión por medios razonables y solicitaremos una nueva aceptación cuando corresponda.' },
        { heading: '9. Contacto', body: 'Para consultas sobre el servicio o reportes de seguridad, escribí a swingersworldinfo@gmail.com. El nombre legal y domicilio del responsable deben verificarse y publicarse antes del lanzamiento.' },
      ],
      note: 'Estos términos no sustituyen las leyes de protección al consumidor ni una revisión jurídica local.',
    },
    privacy: {
      title: 'Política de privacidad',
      updated: 'Versión del 4 de octubre de 2026',
      intro: 'Esta política explica qué datos usa Swingers World, para qué, con quién pueden compartirse y qué controles tenés. Debido a la naturaleza del servicio, el perfil, las preferencias y las conversaciones pueden revelar información especialmente sensible. Decidí cuidadosamente qué compartís.',
      sections: [
        { heading: '1. Responsable y contacto', body: 'Swingers World opera el servicio. Para consultas o solicitudes sobre tus datos, escribí a swingersworldinfo@gmail.com. El nombre legal y domicilio del responsable deben verificarse y publicarse antes del lanzamiento.' },
        { heading: '2. Datos que tratamos', body: 'Recibimos datos de registro y cuenta (nombre, correo, contraseña protegida, verificación y configuración), datos de perfil individual o de pareja (nombre visible, composición, preferencias, descripción, fotos y ubicación que proporcionás), mensajes, interacciones, bloqueos y reportes. También tratamos datos técnicos necesarios para iniciar sesión, enviar notificaciones, prevenir abusos y diagnosticar errores. La tienda y RevenueCat nos comunican identificadores y estados de suscripción; no recibimos el número completo de tu tarjeta.' },
        { heading: '3. Finalidades', body: 'Usamos los datos para crear y proteger la cuenta, mostrar perfiles según las preferencias y ajustes de visibilidad, facilitar chats e interacciones, gestionar fotos privadas y solicitudes de acceso, prestar funciones de suscripción, responder a consultas y reportes, prevenir fraude y cumplir obligaciones legales. No debés incluir datos de terceros en tu perfil sin su autorización.' },
        { heading: '4. Visibilidad y otras personas', body: 'El nombre visible, descripción y fotos configuradas como públicas pueden ser vistos por otras personas de la comunidad. Las fotos privadas dependen de tus controles y de las autorizaciones que otorgues. Los destinatarios pueden conservar capturas o copias fuera de nuestro control; ningún ajuste ofrece privacidad absoluta. Los mensajes son visibles para sus participantes y pueden revisarse cuando hay un reporte o una obligación legal.' },
        { heading: '5. Ubicación y permisos', body: 'Si activás la ubicación, podemos recibir coordenadas o una ubicación aproximada para búsquedas y coincidencias. Podés usar una ubicación manual cuando la función esté disponible y retirar el permiso desde el dispositivo. Cámara, galería, micrófono y notificaciones se usan cuando elegís funciones que los necesitan; podés administrar sus permisos en el sistema operativo.' },
        { heading: '6. Proveedores y transferencias', body: 'Usamos proveedores de alojamiento y almacenamiento, correo, notificaciones y procesamiento de compras, incluidos Google Play, App Store, RevenueCat y la infraestructura configurada para el servicio. Estos proveedores tratan los datos necesarios para prestar sus funciones y pueden operar en otros países. También podemos divulgar datos cuando la ley lo exija o sea necesario para proteger derechos y seguridad.' },
        { heading: '7. Conservación y eliminación', body: 'Conservamos los datos mientras la cuenta esté activa y durante el tiempo adicional necesario para seguridad, disputas, obligaciones fiscales o legales. Podés solicitar la eliminación desde Cuenta > Eliminar cuenta. El servidor elimina la cuenta y los registros asociados que controla; copias de seguridad, registros de seguridad, información de compras retenida por tiendas y copias realizadas por otras personas pueden perdurar según sus reglas y obligaciones aplicables. Cancelá por separado cualquier suscripción en la tienda.' },
        { heading: '8. Seguridad y tus derechos', body: 'Aplicamos medidas técnicas y organizativas razonables para proteger la información, pero ningún servicio puede garantizar seguridad absoluta. Podés editar datos y visibilidad, revocar acceso a fotos privadas, bloquear personas, retirar permisos del dispositivo y eliminar la cuenta. También podés escribirnos para solicitar acceso, rectificación, eliminación u otras opciones que reconozca la ley aplicable.' },
        { heading: '9. Menores y cambios', body: 'El servicio no está dirigido a menores de 18 años. Si detectamos una cuenta de un menor, podemos eliminarla. Si esta política cambia de forma importante, publicaremos la nueva versión y avisaremos por medios razonables; pediremos una nueva confirmación cuando corresponda.' },
      ],
      note: 'La información de esta política debe coincidir con las prácticas reales del servicio y la ficha de seguridad de datos de la tienda.',
    },
  },
  en: {
    terms: {
      title: 'Terms and Conditions',
      updated: 'Version dated October 4, 2026',
      intro: 'These terms govern Swingers World, a platform for adults to meet other adults. Read them before creating an account. The Privacy Policy is a separate document.',
      sections: [
        { heading: '1. Age and account', body: 'The service is only for people aged 18 or older, or the higher legal age where they live. You must provide accurate information, keep your credentials confidential, and not transfer your account. If you create a couple profile, you confirm that both people are adults, know about the profile, and authorize its publication.' },
        { heading: '2. Consent and safety', body: 'All interactions must be voluntary and respectful. Using the app does not imply consent to any activity outside it. Consent may be withdrawn at any time. Do not share another person’s images, messages, or private information without express authorization. Avoid publishing information that could identify or locate you beyond what you intend to share.' },
        { heading: '3. Prohibited conduct and content', body: 'Impersonation, fake profiles, harassment, threats, discrimination, extortion, exploitation, non-consensual sexual content, images of minors, trafficking, prostitution or sexual acts in exchange for money or benefits, spam, and illegal activity are prohibited. Do not post content without the necessary rights or permission. Violations may result in content removal or account suspension.' },
        { heading: '4. Your content', body: 'You retain your rights to content you upload. By posting it, you grant us a non-exclusive permission to store, process, and display it to the people allowed by your settings, solely to operate and protect the service. You may edit or remove content using available features, subject to technical limits and applicable legal obligations.' },
        { heading: '5. Reports and moderation', body: 'You can block or report profiles and content in the app. We may review reports, restrict features, remove content, or suspend accounts to enforce these rules and protect the community. We do not guarantee advance review of all content or the identity, intentions, or conduct of others. For immediate danger, contact local emergency services.' },
        { heading: '6. Subscriptions and free trials', body: 'Price, duration, automatic renewal, and free-trial terms are shown before purchase confirmation in the applicable store. Unless you cancel before the trial ends, the store may charge for the next period. Cancellations are managed through Google Play or the App Store and usually preserve access until the paid period ends. Deleting an account does not itself cancel a subscription. Refunds are governed by store rules and applicable law.' },
        { heading: '7. Availability and limits', body: 'We work to keep the service available and secure, but interruptions, errors, or feature changes may occur. We do not guarantee compatible matches or outcomes of interactions outside the app. Nothing in these terms limits rights that cannot lawfully be excluded.' },
        { heading: '8. Closure and changes', body: 'You can delete your account from Account. We may suspend it for serious violations or security risks. If we materially change these terms, we will communicate the new version by reasonable means and request renewed acceptance where required.' },
        { heading: '9. Contact', body: 'For service questions or safety reports, contact swingersworldinfo@gmail.com. The operator’s legal name and address must be verified and published before launch.' },
      ],
      note: 'These terms do not replace consumer-protection laws or a local legal review.',
    },
    privacy: {
      title: 'Privacy Policy',
      updated: 'Version dated October 4, 2026',
      intro: 'This policy explains what data Swingers World uses, why, who may receive it, and the controls available to you. Because of the nature of this service, profiles, preferences, and conversations may reveal particularly sensitive information. Choose carefully what you share.',
      sections: [
        { heading: '1. Controller and contact', body: 'Swingers World operates the service. For privacy questions or requests, contact swingersworldinfo@gmail.com. The operator’s legal name and address must be verified and published before launch.' },
        { heading: '2. Data we process', body: 'We receive registration and account data (name, email, protected password, verification and settings); individual or couple profile data (display name, composition, preferences, description, photos and location you provide); messages, interactions, blocks and reports. We also process technical data needed for sign-in, notifications, abuse prevention and troubleshooting. Stores and RevenueCat share subscription identifiers and status; we do not receive your full card number.' },
        { heading: '3. Purposes', body: 'We use data to create and protect accounts, show profiles according to preferences and visibility settings, enable chats and interactions, manage private photos and access requests, deliver subscription features, respond to questions and reports, prevent fraud, and meet legal obligations. Do not include third-party data in your profile without permission.' },
        { heading: '4. Visibility and other people', body: 'Your display name, description, and photos set as public may be seen by other community members. Private photos depend on your controls and the access you grant. Recipients may keep screenshots or copies outside our control; no setting guarantees absolute privacy. Messages are visible to their participants and may be reviewed following a report or legal requirement.' },
        { heading: '5. Location and permissions', body: 'If you enable location, we may receive coordinates or an approximate location for search and matching. You can use a manual location where available and withdraw permission in device settings. Camera, gallery, microphone, and notifications are used when you choose features that need them; you can manage these permissions in your operating system.' },
        { heading: '6. Providers and transfers', body: 'We use hosting and storage, email, notification, and purchase-processing providers, including Google Play, the App Store, RevenueCat, and the infrastructure configured for the service. They process data needed to provide their functions and may operate in other countries. We may also disclose information where required by law or necessary to protect rights and safety.' },
        { heading: '7. Retention and deletion', body: 'We keep data while your account is active and for any additional time needed for security, disputes, tax or legal obligations. You can request deletion in Account > Delete account. Our server deletes the account and associated records it controls; backups, security logs, purchase information retained by stores, and copies made by other people may remain under their rules and applicable obligations. Cancel any store subscription separately.' },
        { heading: '8. Security and your rights', body: 'We apply reasonable technical and organizational safeguards, but no service can guarantee absolute security. You can edit data and visibility, revoke private-photo access, block people, withdraw device permissions, and delete your account. You may also contact us to request access, correction, deletion, or other options available under applicable law.' },
        { heading: '9. Children and changes', body: 'The service is not intended for anyone under 18. If we discover a minor’s account, we may delete it. If this policy materially changes, we will publish the new version and notify users by reasonable means; we will request renewed acknowledgment where required.' },
      ],
      note: 'This policy must match the service’s actual practices and the store’s Data safety disclosure.',
    },
  },
};
